# Generated by Django 4.1 on 2022-09-12 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmployeeFirstName', models.CharField(max_length=30)),
                ('EmployeeSecondName', models.CharField(max_length=30)),
                ('EmployeeID', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WeakEmployee',
            fields=[
                ('goodemployee_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='POS.goodemployee')),
                ('EmployeeFeedback', models.TextField()),
            ],
            bases=('POS.goodemployee',),
        ),
    ]
