# Generated by Django 4.1 on 2022-09-14 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0002_goodemployee_weakemployee'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemName', models.CharField(max_length=100)),
                ('ItemQuantity', models.BigIntegerField()),
            ],
        ),
    ]
