# Generated by Django 4.1 on 2022-09-22 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0003_stockmanagement'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfitManagement',
            fields=[
                ('day_count', models.BigAutoField(primary_key=True, serialize=False)),
                ('DailyProfit', models.BigIntegerField()),
                ('MonthlyProfit', models.BigIntegerField()),
                ('YearlyProfit', models.BigIntegerField()),
            ],
        ),
    ]
