# Generated by Django 4.1 on 2023-02-02 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0004_profitmanagement'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='ItemsBought',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='checkout',
            name='TotalPrice',
            field=models.TextField(default=''),
        ),
    ]
